production:
  SECRET_KEY: 1$#okfi6%qis@jjhm6!2%gw%4u!txd9-+^o*4ht0&(%*$mevu*
  DATABASES:
    default:
      DATABASE: postgres
      ENGINE: django.db.backends.postgresql
      NAME: geek_habr_db
      USER: habr_admin
      PASSWORD: habr_admin
      HOST: db
      PORT: 5432