default:
  SECRET_KEY: ''
  ALLOWED_HOSTS:
    - '*'
  DEBUG: True
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3

production:
  DEBUG: False
#  DATABASES:
#    default:
#      ENGINE: django.db.backends.postgresql
#      NAME: geek_habr_db